set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR ppu)
set(TRIPLE ppu-lv2-elf)

set(PS3 1)

set(CMAKE_C_COMPILER "clang")
set(CMAKE_C_COMPILER_TARGET "${TRIPLE}")
set(CMAKE_C_LINK_EXECUTABLE "ld.lld <FLAGS> <CMAKE_C_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o<TARGET> <LINK_LIBRARIES>")

set(CMAKE_CXX_COMPILER "clang++")
set(CMAKE_CXX_COMPILER_TARGET "${TRIPLE}")
set(CMAKE_CXX_LINK_EXECUTABLE "ld.lld <FLAGS> <CMAKE_CXX_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o<TARGET> <LINK_LIBRARIES>")

set(CMAKE_ASM_COMPILER_TARGET "${TRIPLE}")